import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const roboto = Roboto({
  weight:["300","400","500","700"],
  style
  :["italic","normal"],
  subsets: ["latin"]
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <nav>
          <ul className='layout d-flex justify-content-start align-items-center'>
            <li><Link href='/'>Home</Link></li>
            <li><Link href='/game'>Game</Link></li>
            <li><Link href='/registro'>Registro</Link></li>
            <li><Link href='/categories'>Categorias</Link></li>
            <li><Link href='/filter'>Filtros</Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
